remote_theme: loreno-heer/minimal
title: "Loreno Heer"
description:   <img src="cvphot2.jpg" alt="photo of me"><br/>
               <br/>
               <br/><br/>
               <script type="text/javascript">gen_mail_to_link('loreno.heer','math.ch','email');</script>
show_downloads: false
markdown: kramdown
