remote_theme: loreno-heer/minimal
title: "Loreno Heer"
logo: /assets/img/cvphot2.jpg
cv: /cv.pdf
description:   
lhtext:        <br/><br/>
               <a href="/blog/">Blog</a><br/>
               <script type="text/javascript">gen_mail_to_link('loreno.heer','math.ch','email');</script>
show_downloads: false
markdown: kramdown
google_analytics: G-K9EBNZ3VFP