remote_theme: loreno-heer/minimal
title: "Loreno Heer"
description:   Loreno Heer </br>
               Institut f체r Mathematik</br>
               Universit채t Z체rich</br>
               Winterthurerstrasse 190</br>
               CH-8057 Z체rich
show_downloads: false
markdown: kramdown
