remote_theme: loreno-heer/minimal
title: "Loreno Heer"
description:   Office G25 <br/>
               Institut f체r Mathematik<br/>
               Universit채t Z체rich<br/>
               Winterthurerstrasse 190<br/>
               CH-8057 Z체rich <br/> <br/>
               <script type="text/javascript">gen_mail_to_link('loreno.heer','math.ch','email');</script>
show_downloads: false
markdown: kramdown
