remote_theme: loreno-heer/minimal
title: "Loreno Heer"
description:   <img src="/cvphot2.jpg" alt="photo of me" style="width:50%;height:50%;"><br/>
               <br/>
               <br/>
	       <a href="/CVeng.pdf">Curriculum vitae</a><br/>
               <script type="text/javascript">gen_mail_to_link('loreno.heer','math.ch','email');</script>
show_downloads: false
markdown: kramdown
