remote_theme: loreno-heer/minimal
title: "Loreno Heer"
logo: /assets/cvphot2.jpg
description:   <br/><br/>
               <br/>
               <script type="text/javascript">gen_mail_to_link('loreno.heer','math.ch','email');</script>
show_downloads: false
markdown: kramdown
