remote_theme: loreno-heer/minimal
title: "Loreno Heer"
description:   Postal Address: <br/>
               Haldenstrasse 132<br/>
               3014 Bern<br/>
               Switzerland<br/><br/>
               <script type="text/javascript">gen_mail_to_link('loreno.heer','math.ch','email');</script>
show_downloads: false
markdown: kramdown
