remote_theme: loreno-heer/minimal
title: "Loreno Heer"
description: "Loreno Heer\nInstitut f체r Mathematik\nUniversit채t Z체rich\nWinterthurerstrasse 190\nCH-8057 Z체rich"
show_downloads: false
markdown: kramdown
