remote_theme: loreno-heer/minimal
title: "Loreno Heer"
description: | Loreno Heer
               Institut f체r Mathematik
               Universit채t Z체rich
               Winterthurerstrasse 190
               CH-8057 Z체rich
show_downloads: false
markdown: kramdown
