remote_theme: loreno-heer/minimal
title: "Loreno Heer"
tagline: Website of Dr. sci. nat. Loreno Heer, Mathematician
logo: /assets/img/cvphot2.jpg
cv: /cv.pdf
description:   Website of Dr. sci. nat. Loreno Heer, Mathematician
lhtext:        <br/><br/>
               <a href="/blog/">Blog</a><br/>
               <script type="text/javascript">gen_mail_to_link('loreno.heer','math.ch','email');</script>
show_downloads: false
markdown: kramdown
google_analytics: G-K9EBNZ3VFP


author:
  name: Loreno Heer
  twitter: loreno_heer
  url: https://loreno-heer.github.io/
  picture: /assets/img/cvphot2.jpg
  
twitter:
  username: loreno_heer
  card: summary
  
social:
  name: Loreno Heer
  links:
    - https://twitter.com/loreno_heer
    - https://www.linkedin.com/in/loreno-heer-8023585/
    - https://stackexchange.com/users/3229416/loreno-heer


url: "https://loreno-heer.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  